spring.application.name=olioshop

# Configurazione Connessione MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/olioshop_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@Akanji_5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/olioshop-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/olioshop-realm
jwt.auth.converter.resource-id=olioshop-client
jwt.auth.converter.principle-attribute=preferred_username